### ISSUE TITLE
recursice anchors cause stackoverflow exception

### ISSUE THREAD

**Issue by elonderin** [de-jcup/eclipse-yaml-editor#93]
in my gitlab yaml i did this accidentally:

```yaml
.env-vars: &env-vars
  - 'echo -e "section_start:`date +%s`:envvars\r\e[0Kenvvars" '
  - *env-vars
  - 'echo -e "section_end:`date +%s`:envvars\r\e[0Kenvvars" '
```
and when opening the quick outline i got a famous:

```
java.lang.StackOverflowError
	at de.jcup.yamleditor.script.YamlScriptModelBuilder.appendSequence(YamlScriptModelBuilder.java:162)
	at de.jcup.yamleditor.script.YamlScriptModelBuilder.buildNode(YamlScriptModelBuilder.java:107)
	at de.jcup.yamleditor.script.YamlScriptModelBuilder.createYamlNodeAndAddToParent(YamlScriptModelBuilder.java:185)
	at de.jcup.yamleditor.script.YamlScriptModelBuilder.appendSequence(YamlScriptModelBuilder.java:162)
...
```

note: when re-opening the editor the outline view is empty

**Comment by de-jcup** [comment]
Yes, was able to reproduce this problem/bug. Thanks for reporting. W

**Comment by de-jcup** [comment]
A good example for anchors and aliases in yaml can be found at
https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
